# Generated by Django 3.2 on 2021-05-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedata',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='servicedata',
            name='name',
        ),
        migrations.AddField(
            model_name='servicedata',
            name='des',
            field=models.CharField(default='123', max_length=1000),
        ),
        migrations.AddField(
            model_name='servicedata',
            name='head',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
